import AppController from "../app.controller";
import { Request, Response } from "express";
import {
  extractURLPathSegmentValue,
  log,
  removeTrailingSlash,
} from "../../utils";
import url from "url";
import axios, { AxiosResponse } from "axios";
import { IncomingHttpHeaders } from "http";
import { ATSUserTokenResponse } from "@vonq/hapi-elements-types";
import https from "https";
import { User, UserID } from "../user/types";

export default class VONQHAPIController {
  backendURL: string =
    process.env.HAPI_BACKEND_ENDPOINT ||
    "https://marketplace-sandbox.api.vonq.com";
  backendHost: string | null = url.parse(this.backendURL).host;

  // if your backend does not work with Bearer TOKENHERE, then you can change this
  // Documentation: https://docs.elements-sandbox.hapi.vonq.com/docs/javascript-api/api/
  ourAuthTokenPrefix: string = "Bearer ";
  // if your backend does not work with X-Authorization key, then you can change this
  // Documentation: https://docs.elements-sandbox.hapi.vonq.com/docs/javascript-api/api/
  ourAuthTokenKey: string = "x-authorization";

  ourHAPIProxyPath = "/api/integrations/vonq";
  allRoutePaths: string = `${this.ourHAPIProxyPath}/*`;
  generateJWTTokenPath: string = `${this.ourHAPIProxyPath}/generate-jwt-token/`;
  refreshJWTTokenPath: string = `${this.ourHAPIProxyPath}/v3/ats/atsuser/me/refresh-jwt-token/`;

  constructor(private appController: AppController) {}

  getProxyPath = (
    urlPath: string | null,
    shouldRemoveTrailingSlash: boolean = false
  ) => {
    let path = urlPath?.replace(this.ourHAPIProxyPath, "");

    if (shouldRemoveTrailingSlash) {
      // some paths may have trailing slash
      path = removeTrailingSlash(path!);
    }

    return path;
  };

  log = (...args: any[]) => {
    log("[VONQHAPIController]", ...args);
  };

  getProxyRequestOptions = (
    req: Request,
    vonqHAPIPath: string,
    modifiedHeaders: IncomingHttpHeaders
  ) => {
    const newUrl = this.backendURL + vonqHAPIPath;

    return {
      method: req.method, // Forward the same method (GET, POST, PUT, DELETE, etc.)
      url: newUrl, // Use the modified URL
      headers: {
        ...modifiedHeaders,
        Host: this.backendHost,
      }, // Forward the same headers
      data: req.body, // Forward the same body if applicable (for POST, PUT, etc.)
      httpsAgent: new https.Agent({
        rejectUnauthorized: false, // Disable SSL certificate validation
      }), // Use the custom agent to bypass SSL validation
    };
  };

  generateTokenForTenant = async (tenantId: string) => {
    try {
      const vonqHAPITokenResponse: AxiosResponse<ATSUserTokenResponse> =
        await axios.post(
          `${this.backendURL}/v3/ats/users/${tenantId}/generate-jwt-token/`,
          {},
          {
            headers: {
              "X-AUTH-TOKEN": process.env.HAPI_BACKEND_PARTNER_TOKEN,
            },
          }
        );

      // for access control, you should pass
      // OWN CUSTOM TOKEN generated by YOUR BACKEND and pass it to your frontend
      // then attach the token on the HAPI Elements Injector as 'clientToken'
      // when HAPI Elements makes requests to your backend proxy
      // verify your own custom token. then pass the HAPI Backend Token
      // while making requests to HAPI Backend
      this.appController.tenantController.updateByID(tenantId, {
        hapiAccessToken: vonqHAPITokenResponse.data.token,
      });

      return vonqHAPITokenResponse.data.token;
    } catch (error) {
      throw error;
    }
  };

  getUserFromRequestHeaders = (headers: IncomingHttpHeaders) => {
    const userAccessTokenWithBearer = headers[this.ourAuthTokenKey] as string;
    const userAccessToken = userAccessTokenWithBearer?.replace(
      this.ourAuthTokenPrefix,
      ""
    );
    const user =
      this.appController.userController.findByAccessToken(userAccessToken);

    return user;
  };

  onRefreshJWTTokenRequest = async (req: Request, res: Response) => {
    const user = this.getUserFromRequestHeaders(req.headers);
    if (user) {
      const tenantIdOfUser = user?.tenantId;
      if (tenantIdOfUser) {
        const tenantOfUser =
          this.appController.tenantController.findByID(tenantIdOfUser);

        if (tenantOfUser) {
          try {
            await this.generateTokenForTenant(tenantOfUser.id);

            // Respond to HAPI Elements with your OWN JWT TOKEN of User
            // this is not your own JWT token refresh but HAPI Elements JWT token refresh
            // so the only token that you should refresh is the hapiAccessToken on Tenant object
            const data: ATSUserTokenResponse = {
              token: user!.accessToken,
            };

            // this.log("onRefreshJWTTokenRequest responding with data", data);

            return this.appController.respondWithData(res, 200, data);
          } catch (error) {
            return this.appController.respondWithAxiosError(res, error);
          }
        } else {
          return this.appController.authController.respondWithUserNotFoundError(
            res
          );
        }
      } else {
        // this.log("onRefreshJWTTokenRequest could not find user");
        return this.appController.authController.respondWithUserNotFoundError(
          res
        );
      }
    } else {
      return this.appController.authController.respondWithUserNotFoundError(
        res
      );
    }
  };

  onGenerateJWTTokenRequest = async (req: Request, res: Response) => {
    // this.log("onGenerateJWTTokenRequest received request");

    // Because HAPI_BACKEND_PARTNER_TOKEN should not leak on your frontend
    // This is where you generate a HAPI JWT Token for your user
    // Documentation: https://docs.elements-sandbox.hapi.vonq.com/docs/getting-started/setting-up/

    // Check what 'clientId' refers to in terms of multi tenancy
    // The function getClientId supports both multi-tenant and single user approaches
    // Documentation: https://docs.elements-sandbox.hapi.vonq.com/docs/getting-started/setting-up/#understanding-multi-tenancy

    // At this stage, you know which of your clients is making this request
    // most likely through JWT
    // for the purpose of this example, we hardcoded the user here
    // get the tenantId of the user
    // you can change the role passed to the function to mimic auth of a different role
    const exampleUserId =
      req.body?.clientId ||
      this.appController.userController.getExampleUserIDByRoleType("admin");
    const exampleUser =
      this.appController.userController.findByID(exampleUserId);
    const tenantIdOfUser = exampleUser?.tenantId;
    if (tenantIdOfUser) {
      const tenantOfUser =
        this.appController.tenantController.findByID(tenantIdOfUser);

      if (tenantOfUser) {
        try {
          await this.generateTokenForTenant(tenantOfUser.id);

          // Respond to HAPI Elements with your OWN JWT TOKEN of User
          const data: ATSUserTokenResponse = {
            token: exampleUser!.accessToken,
          };

          // this.log("onGenerateJWTTokenRequest responding with data", data);

          return this.appController.respondWithData(res, 200, data);
        } catch (error) {
          return this.appController.respondWithAxiosError(res, error);
        }
      } else {
        return this.appController.authController.respondWithUserNotFoundError(
          res
        );
      }
    } else {
      // this.log("onGenerateJWTTokenRequest could not find user");
      return this.appController.authController.respondWithUserNotFoundError(
        res
      );
    }
  };

  onProxyRequest = async (req: Request, res: Response) => {
    try {
      const parsedUrl = url.parse(req.originalUrl, true);
      const vonqHAPIPath = this.getProxyPath(parsedUrl.path);
      const vonqHAPIPathWithoutTrailingSlash = this.getProxyPath(
        parsedUrl.path,
        true
      )!;

      this.log(
        "onProxyRequest received request for path",
        parsedUrl.path,
        "with headers",
        req.headers
      );

      const user = this.getUserFromRequestHeaders(req.headers);
      //this.log("onProxyRequest got user", user);

      if (user) {
        const tenantOfUser = this.appController.tenantController.findByID(
          user.tenantId
        );
        if (tenantOfUser) {
          let modifiedHeaders = req.headers;

          //this.log("onProxyRequest found tenant", tenantOfUser);

          // request has your own custom token
          // you should check if user is authorized
          // then if not authorized, return 401 response
          // HAPI Elements will show a toast notification with your response message
          // this behavior can be customized
          // Documentation: https://docs.elements-sandbox.hapi.vonq.com/docs/customization/implementing-access-control/
          try {
            this.appController.authController.throwErrorWhenNotAuthorized(
              user.accessToken,
              vonqHAPIPathWithoutTrailingSlash,
              req
            );
            // change the Authorization header so that your own custom token is not sent to backend
            // instead the HAPI Backend JWT Token should be sent
            modifiedHeaders = {
              ...modifiedHeaders,
              // X-Authorization: Bearer TOKENHERE is required when making requests to HAPI Backend
              ["X-Authorization"]: `Bearer ${tenantOfUser.hapiAccessToken}`,
            };
          } catch (error) {
            return this.appController.authController.respondWithUnauthorizedError(
              res
            );
          }

          // Create the options object to forward the request with the same method, headers, and data
          const options = this.getProxyRequestOptions(
            req,
            vonqHAPIPath!,
            modifiedHeaders
          );

          // Send the request to the external API
          const axiosResponse = await axios(options);

          this.onAfterHAPIBackendSuccessResponse(req, user, axiosResponse);

          // this.log("onProxyRequest responding with response", response);

          return this.appController.respondWithAxiosResponse(
            res,
            axiosResponse
          );
        } else {
          return this.appController.authController.respondWithUserNotFoundError(
            res
          );
        }
      } else {
        //this.log("onProxyRequest could not find user");
        return this.appController.authController.respondWithUserNotFoundError(
          res
        );
      }
    } catch (error) {
      //this.log("onProxyRequest failed with error", error);
      return this.appController.respondWithAxiosError(res, error);
    }
  };

  onAfterHAPIBackendSuccessResponse = (
    req: Request,
    user: User,
    hapiBackendResponse: AxiosResponse<any>
  ) => {
    const { tenantVONQResourceController } = this.appController;
    const { upsertDataByVONQResourceID } = tenantVONQResourceController;

    const parsedUrl = url.parse(req.originalUrl, true);
    const vonqHAPIPath = this.getProxyPath(parsedUrl.path, true)!;

    const responseData = hapiBackendResponse.data;

    // Save IDs sent by HAPI Backend in a Tenant VONQ Resource table
    // For both auditing purposes and ROW based access control
    if (req.method !== "GET") {
      this.log(
        "onAfterHAPIBackendSuccessResponse received request for path",
        vonqHAPIPath,
        "with method",
        req.method,
        "and received HAPI Backend response data",
        responseData
      );
    }

    if (vonqHAPIPath.startsWith("/igb/contracts/groups")) {
      upsertDataByVONQResourceID(
        responseData.idx || //IDX is used on HAPI Backend for GET, PUT, PATCH, DELETE
          extractURLPathSegmentValue(vonqHAPIPath, "/igb/contracts/groups/"),
        "contract-group",
        req.method,
        user.id
      );
    } else if (vonqHAPIPath.startsWith("/contracts")) {
      upsertDataByVONQResourceID(
        responseData.contract_id ||
          extractURLPathSegmentValue(vonqHAPIPath, "/contracts/"),
        "contract",
        req.method,
        user.id
      );
    } else if (vonqHAPIPath.endsWith("/wallet")) {
      upsertDataByVONQResourceID(
        responseData.id || extractURLPathSegmentValue(vonqHAPIPath, "/wallet"),
        "wallet",
        req.method,
        user.id
      );
    } else if (vonqHAPIPath.startsWith("/campaigns")) {
      upsertDataByVONQResourceID(
        responseData.campaignId ||
          extractURLPathSegmentValue(vonqHAPIPath, "/campaigns/"),
        "campaign",
        req.method,
        user.id
      );
    }

    this.log(
      "onAfterHAPIBackendSuccessResponse finished",
      tenantVONQResourceController.findAll()
    );
  };
}
